### PR TITLE
Add file monitor

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Monitor .nim files for change

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
@theduke are your projects still alive?

**Comment by theduke** [comment]
@FedericoCeratto  sadly I wont have time for anything nim-related in the near future.

If you would like to take over any of the projects, I would gladly transfer the ownership over to you.

**Comment by FedericoCeratto** [comment]
Yes please. Can we discuss the transfer over email or IRC?

**Comment by watzon** [comment]
@FedericoCeratto I just took over this project, so I'll be looking into merging this

**Comment by FedericoCeratto** [comment]
@watzon thanks for the update. While omega was inactive I put together a framework-agnostic test runner: https://github.com/FedericoCeratto/nim-testrunner/

**Pull request closed without merging**
